### ISSUE TITLE
Since yesterday unique click counter doesn't work anymore, it's equal to click counter.

### ISSUE THREAD

**Issue by Zovi3U** [spoo-me/url-shortener#32]

**Comment by Zingzy** [comment]
Hello @Zovi3U could you please send me some affected URLs which you encountered?

**Comment by Zingzy** [comment]
Hello @Zovi3U, thanks for pointing out the issue. We recently updated the URL statistics logic to optimize the redirection time, and while the update worked, it introduced a bug. We’ve identified the problem and will have it fixed by the end of the day.

**Comment by Zingzy** [comment]
![image](https://github.com/user-attachments/assets/f6749bba-78a1-4bd2-9e63-66f3db0c7f08)
@Zovi3U The bug is fixed successfully, thanks for pointing it out!
