### ISSUE TITLE
Question about Copyright Name / Year, attribution

### ISSUE THREAD

**Issue by solderq35** [spoo-me/url-shortener#4]
## Issue

https://github.com/spoo-me/url-shortener/blob/51bfc8dafa40d0a0e08a061000e813899f9c9683/LICENSE#L189

Hi @Zingzy / spoo-me, I noticed that your copyright file is missing a specific name and year, so I was not sure if I will get in any legal trouble if I fork off of your repository as is.

## My Request

- **Please let me know if you plan to add your name (or just your github username for privacy maybe, I am not a lawyer) and also a date to the copyright file before I fork / clone it, just in case of legal issues.**
  - **I am happy to wait for you to make any edits needed to the copyright before trying to fork and modify your code**
- If you don't think it's necessary to change the LICENSE, let me know, it's fine to me either way
- Similarly, outside of the LICENSE (e.g. on the frontend of my fork), would you like me to credit you in any specific format? Would linking to the spoo.me twitter (https://twitter.com/spoo_me) suffice, or maybe to your personal twitter as well (https://twitter.com/zingzy3)?

I am broadly aware that the Apache 2 license means I must preserve the original copyright, and that I must give an overview of any changes I make to the code compared to the original project (hence my question about whether your current copyright details are correct).

As outlined by Apache Foundation guidelines, I was thinking about appending my own copyright onto the original LICENSE, making sure to keep the original LICENSE content unchanged but just adding my own name / date for the change I plan to make, as well as adding a NOTICE file explaining any changes made. Does that sound fair to you, along with possibly giving credit to you on the frontend of my fork as mentioned earlier?

## Other Background Context about this request

I was planning to fork or clone this repo and make some adjustments for my own usage, and I don't plan to merge my custom version back into the original at this time (hence why I used fork and clone interchangeably), as I think I have a more narrow scope of usage in mind (for example, I don't think I will need the emoji URL's, and I want to set some custom CORS headers potentially).

I would be self-hosting my own Mongo database as well as the backend / frontend.

I would also be happy to contribute back to the original project in the future (not on my custom fork), so feel free to write up some more GitHub Issues about things you might appreciate help with.

Sorry if that got long-winded for a simple request, best regards.

**Comment by Zingzy** [comment]
Hi there,

Thank you so much for reaching out and for your interest in spoo.me URL shortener project. I’ve updated the LICENSE file to include the correct year and my GitHub username for clarity. You should now be able to fork or clone the repository without any legal concerns.

I’m really thankful that you’ve selected my URL shortening service for your use. Please feel free to modify it in your own fork as you see fit. I’m also quite curious and would love to see your custom fork if you’re willing to share it!

Regarding the credit, just mentioning the repository in your fork is absolutely fine. There’s no need for specific links to any social media unless you prefer to do so.

Your approach to appending your own copyright onto the original LICENSE and adding a NOTICE file explaining any changes made is spot on and very much appreciated. It’s fair and aligns well with the Apache 2 license guidelines.

It’s great to hear that you’re considering contributing back to the original project in the future. I’m always open to collaboration and would welcome any improvements or ideas you have. 😊

**Comment by solderq35** [comment]
Thank you! Issue seems resolved to me.
